SUBROUTINE FEXD( NumG, T, Y, YDOT, RPAR, IPAR)

	IMPLICIT NONE

	INTEGER, INTENT(IN) :: NumG, IPAR
	DOUBLE PRECISION, INTENT(IN) :: T
	DOUBLE COMPLEX, INTENT(IN) :: Y(NumG), RPAR(NumG**2)
	DOUBLE COMPLEX, INTENT(OUT) :: YDOT(NumG)
	DOUBLE COMPLEX :: R(NumG,NumG)

	R(1:NumG,1:NumG) = RESHAPE( RPAR, (/ NumG, NumG /))
	YDOT(1:NumG) = MATMUL( R, Y )
	RETURN

END SUBROUTINE FEXD
