SUBROUTINE potential_energy(x,params,V)

	IMPLICIT NONE
	DOUBLE PRECISION, INTENT(IN) :: x
	DOUBLE PRECISION, INTENT(IN) :: params(15)
	DOUBLE PRECISION, INTENT(OUT) :: V

	V = 1.0D-5 * x * x 
	RETURN

END SUBROUTINE potential_energy

SUBROUTINE diff_potential_energy(x,params,dV)

	IMPLICIT NONE
	DOUBLE PRECISION, INTENT(IN) :: x
	DOUBLE PRECISION, INTENT(IN) :: params(15)
	DOUBLE PRECISION, INTENT(OUT) :: dV

	dV = 2.0D-5 * x
	RETURN

END SUBROUTINE diff_potential_energy

SUBROUTINE diff2_potential_energy(x,params,d2V)

	IMPLICIT NONE
	DOUBLE PRECISION, INTENT(IN) :: x
	DOUBLE PRECISION, INTENT(IN) :: params(15)
	DOUBLE PRECISION, INTENT(OUT) :: d2V

	d2V = 2.0D-5
	RETURN

END SUBROUTINE diff2_potential_energy

SUBROUTINE diff3_potential_energy(x,params,d3V)

	IMPLICIT NONE
	DOUBLE PRECISION, INTENT(IN) :: x
	DOUBLE PRECISION, INTENT(IN) :: params(15)
	DOUBLE PRECISION, INTENT(OUT) :: d3V

	d3V = 0.0D0
	RETURN

END SUBROUTINE diff3_potential_energy
