SUBROUTINE FEXq( NEQ, T, Y, YDOT, RPAR, IPAR )

	DOUBLE PRECISION, INTENT(IN) :: T, RPAR(2) 
	DOUBLE COMPLEX :: Y, YDOT

	YDOT = DCMPLX( RPAR(1) / RPAR(2), 0.0D0 )
	RETURN

END SUBROUTINE

SUBROUTINE FEXp( NEQ, T, Y, YDOT, RPAR, IPAR )

	DOUBLE PRECISION, INTENT(IN) :: T, RPAR(16)
	DOUBLE PRECISION :: dV
	DOUBLE COMPLEX :: Y, YDOT

	CALL diff_potential_energy( RPAR(1), RPAR(2:16), dV )

	YDOT = DCMPLX( -dV, 0.0D0 )
	RETURN

END SUBROUTINE FEXp
